/**
 * This class is generated by jOOQ
 */
package org.jooq.util.maven.example;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the demoproject2 schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.3"},
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({"unchecked"})
public class Keys extends org.jooq.impl.AbstractKeys {

	// IDENTITY definitions

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<org.jooq.util.maven.example.tables.records.CustomerRecord> KEY_customer_PRIMARY = createUniqueKey(org.jooq.util.maven.example.tables.Customer.CUSTOMER, org.jooq.util.maven.example.tables.Customer.CUSTOMER.ID);
	public static final org.jooq.UniqueKey<org.jooq.util.maven.example.tables.records.EmployeeRecord> KEY_employee_PRIMARY = createUniqueKey(org.jooq.util.maven.example.tables.Employee.EMPLOYEE, org.jooq.util.maven.example.tables.Employee.EMPLOYEE.ID);

	// FOREIGN KEY definitions

	/**
	 * No instances
	 */
	private Keys() {}
}
