/**
 * This class is generated by jOOQ
 */
package org.jooq.util.maven.example;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in demoproject2
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.3"},
                            comments = "This class is generated by jOOQ")
public final class Tables {

	/**
	 * The table demoproject2.customer
	 */
	public static org.jooq.util.maven.example.tables.Customer CUSTOMER = org.jooq.util.maven.example.tables.Customer.CUSTOMER;

	/**
	 * The table demoproject2.employee
	 */
	public static org.jooq.util.maven.example.tables.Employee EMPLOYEE = org.jooq.util.maven.example.tables.Employee.EMPLOYEE;

	/**
	 * No instances
	 */
	private Tables() {}
}
