/**
 * This class is generated by jOOQ
 */
package org.jooq.util.maven.example.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.3"},
                            comments = "This class is generated by jOOQ")
public class Customer extends org.jooq.impl.UpdatableTableImpl<org.jooq.util.maven.example.tables.records.CustomerRecord> {

	private static final long serialVersionUID = -531744887;

	/**
	 * The singleton instance of customer
	 */
	public static final org.jooq.util.maven.example.tables.Customer CUSTOMER = new org.jooq.util.maven.example.tables.Customer();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<org.jooq.util.maven.example.tables.records.CustomerRecord> __RECORD_TYPE = org.jooq.util.maven.example.tables.records.CustomerRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.util.maven.example.tables.records.CustomerRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.util.maven.example.tables.records.CustomerRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<org.jooq.util.maven.example.tables.records.CustomerRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * No further instances allowed
	 */
	private Customer() {
		super("customer", org.jooq.util.maven.example.Demoproject2.DEMOPROJECT2);
	}

	/**
	 * No further instances allowed
	 */
	private Customer(java.lang.String alias) {
		super(alias, org.jooq.util.maven.example.Demoproject2.DEMOPROJECT2, org.jooq.util.maven.example.tables.Customer.CUSTOMER);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.util.maven.example.tables.records.CustomerRecord> getMainKey() {
		return org.jooq.util.maven.example.Keys.KEY_customer_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.util.maven.example.tables.records.CustomerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.util.maven.example.tables.records.CustomerRecord>>asList(org.jooq.util.maven.example.Keys.KEY_customer_PRIMARY);
	}

	@Override
	public org.jooq.util.maven.example.tables.Customer as(java.lang.String alias) {
		return new org.jooq.util.maven.example.tables.Customer(alias);
	}
}
