/**
 * This class is generated by jOOQ
 */
package org.jooq.util.maven.example.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.3"},
                            comments = "This class is generated by jOOQ")
public class Employee extends org.jooq.impl.UpdatableTableImpl<org.jooq.util.maven.example.tables.records.EmployeeRecord> {

	private static final long serialVersionUID = -1551909895;

	/**
	 * The singleton instance of employee
	 */
	public static final org.jooq.util.maven.example.tables.Employee EMPLOYEE = new org.jooq.util.maven.example.tables.Employee();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<org.jooq.util.maven.example.tables.records.EmployeeRecord> __RECORD_TYPE = org.jooq.util.maven.example.tables.records.EmployeeRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.util.maven.example.tables.records.EmployeeRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<org.jooq.util.maven.example.tables.records.EmployeeRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<org.jooq.util.maven.example.tables.records.EmployeeRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * No further instances allowed
	 */
	private Employee() {
		super("employee", org.jooq.util.maven.example.Demoproject2.DEMOPROJECT2);
	}

	/**
	 * No further instances allowed
	 */
	private Employee(java.lang.String alias) {
		super(alias, org.jooq.util.maven.example.Demoproject2.DEMOPROJECT2, org.jooq.util.maven.example.tables.Employee.EMPLOYEE);
	}

	@Override
	public org.jooq.UniqueKey<org.jooq.util.maven.example.tables.records.EmployeeRecord> getMainKey() {
		return org.jooq.util.maven.example.Keys.KEY_employee_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.jooq.util.maven.example.tables.records.EmployeeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.util.maven.example.tables.records.EmployeeRecord>>asList(org.jooq.util.maven.example.Keys.KEY_employee_PRIMARY);
	}

	@Override
	public org.jooq.util.maven.example.tables.Employee as(java.lang.String alias) {
		return new org.jooq.util.maven.example.tables.Employee(alias);
	}
}
