/**
 * This class is generated by jOOQ
 */
package org.jooq.util.maven.example.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.3"},
                            comments = "This class is generated by jOOQ")
public class EmployeeRecord extends org.jooq.impl.UpdatableRecordImpl<org.jooq.util.maven.example.tables.records.EmployeeRecord> {

	private static final long serialVersionUID = -1321195637;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.jooq.util.maven.example.tables.Employee.EMPLOYEE.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.jooq.util.maven.example.tables.Employee.EMPLOYEE.ID);
	}

	/**
	 * An uncommented item
	 */
	public void setName(java.lang.String value) {
		setValue(org.jooq.util.maven.example.tables.Employee.EMPLOYEE.NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getName() {
		return getValue(org.jooq.util.maven.example.tables.Employee.EMPLOYEE.NAME);
	}

	/**
	 * Create a detached EmployeeRecord
	 */
	public EmployeeRecord() {
		super(org.jooq.util.maven.example.tables.Employee.EMPLOYEE);
	}
}
